-- Egypt's 27 governorates. Districts are intentionally left empty for V1 — populate
-- via the admin panel or a follow-up import once real district-level data is sourced.
insert into governorates (name_ar, name_en) values
  ('القاهرة', 'Cairo'),
  ('الجيزة', 'Giza'),
  ('الإسكندرية', 'Alexandria'),
  ('الدقهلية', 'Dakahlia'),
  ('البحر الأحمر', 'Red Sea'),
  ('البحيرة', 'Beheira'),
  ('الفيوم', 'Fayoum'),
  ('الغربية', 'Gharbia'),
  ('الإسماعيلية', 'Ismailia'),
  ('المنوفية', 'Monufia'),
  ('المنيا', 'Minya'),
  ('القليوبية', 'Qalyubia'),
  ('الوادي الجديد', 'New Valley'),
  ('السويس', 'Suez'),
  ('أسوان', 'Aswan'),
  ('أسيوط', 'Asyut'),
  ('بني سويف', 'Beni Suef'),
  ('بورسعيد', 'Port Said'),
  ('دمياط', 'Damietta'),
  ('الشرقية', 'Sharqia'),
  ('جنوب سيناء', 'South Sinai'),
  ('كفر الشيخ', 'Kafr El Sheikh'),
  ('مطروح', 'Matrouh'),
  ('الأقصر', 'Luxor'),
  ('قنا', 'Qena'),
  ('شمال سيناء', 'North Sinai'),
  ('سوهاج', 'Sohag');
